"""
Basic Matrix Calculations and Operations:

The basis for these calculation is the python list. So, this is only for insight and education, not performance.
"""

from typing import List, Tuple, Callable

Matrix = List[List[float]]


def shape(A: Matrix) -> Tuple[int, int]:
    """Returns (# of rows of A, # of columns of A)"""

    num_rows = len(A)
    num_cols = len(A[0])

    return num_rows, num_cols


def get_row(A: Matrix, i: int) -> List[float]:
    """Returns the ith row of Matrix A"""

    return A[i]


def get_column(A: Matrix, i: int) -> List[float]:
    """Returns the ith column of Matrix A"""

    return [x[i] for x in A]


def make_matrix(num_rows: int, num_cols: int, entry_fn: Callable[[int, int], float]) -> Matrix:

    """returns an Matrix with num_rows and num_cols.
        whose (i,j)th entry is generated by the entry function (i,j)"""

    return [[entry_fn(i, j)             # given i, create a list
            for j in range(num_cols)]   # [entry)fun(i, 0), ... ]
            for i in range(num_rows)]   # create one list for each i


def identity_matrix(num: int) -> Matrix:
    """Generates a matrix with num rows and num columns"""

    return make_matrix(num, num, lambda i, j: 1 if i == j else 0)

